apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-vault-secrets
  namespace: petclinic
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: petclinic-vault-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: jdbc-uri
      remoteRef:
        key: petclinic/db
        property: jdbc-uri
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: user
      remoteRef:
        key: petclinic/db
        property: user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: petclinic/db
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
