apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-pgbackrest-s3-creds
  namespace: petclinic
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: petclinic-pgbackrest-s3-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      mergePolicy: Replace
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ "{{ .accessKey }}" }}
          repo1-s3-key-secret={{ "{{ .secretKey }}" }}
  data:
    - secretKey: accessKey
      remoteRef:
        key: petclinic/r2-backup
        property: access-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secretKey
      remoteRef:
        key: petclinic/r2-backup
        property: secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
