image:
  repository: petabait/spring-petclinic
  tag: "dbe338b"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
