apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      mergePolicy: Replace
      data:
        admin-user: "{{ .adminUser }}"
        admin-password: "{{ .adminPassword }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: grafana       # путь в KV: secret/grafana (mount "secret" уже задан в ClusterSecretStore)
        property: pass  # имя поля внутри секрета, как ты его создал в Vault UI
    - secretKey: adminUser
      remoteRef:
        key: grafana     
        property: user
