apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: permissive-mtls
  namespace: vault
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: permissive-mtls #strict-mtls
  namespace: external-secrets
spec:
  mtls:
    mode: PERMISSIVE #STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: permissive-mtls
  namespace: petclinic
spec:
  mtls:
    mode: PERMISSIVE
